## Import Libraries

In [1]:
import pandas as pd
import numpy as np

## Data Import

In [2]:
fatherhood = pd.read_csv("Fatherhood.csv")

participation = pd.read_csv("Participation.csv")

## Convert Client ID from float to string to allow merge

In [3]:
survey["Client ID"] = (
    survey["Client ID"]
    .astype("Int64")
    .astype("string")
)

participation["Client ID"] = (
    participation["Client ID"]
    .astype("Int64")
    .astype("string")
)

## Drop blank columns ##

In [4]:
survey = survey.dropna(axis=1, how='all')
participation = participation.dropna(axis=1, how='all')

## Replace empty and whitespace cells ##

Blank string values were standardized to NaN using regex-based replacement to ensure consistent missing value handling across the dataset. This step aligned all forms of empty responses (e.g., whitespace-only entries) with pandas’ native missing value representation, enabling accurate filtering and aggregation in downstream analysis and Tableau/Power BI visualizations.

Note: Null values were retained in the dataset to preserve data integrity, but excluded from most visualizations where they were not analytically relevant. Categorical fields contained minimal missingness, while missing numeric values were largely structural (i.e., dependent on survey design and respondent routing), rather than indicative of data quality issues. No imputation was performed, as missingness primarily reflected survey design and response structure rather than data quality issues.

In [5]:
survey = survey.replace(r'^\s*$', np.nan, regex=True)
participation = participation.replace(r'^\s*$', np.nan, regex=True)

## Keep only pertinent columns in 'participation' data frame

Most fields in 'participation' dataset are redundant/identical to those in fatherhood dataset. This command only keeps Client ID for merging and Primary Workshop Hours for additional analysis.

In [35]:
keep_columns = ["Client ID", "Participation in Primary Workshop(s) Hours"]

participation = participation[keep_columns]

In [7]:
participation.head(1)

  Client ID  Participation in Primary Workshop(s) Hours
0  10845077                                          16

## Merge datasets on Client ID

In [8]:
fatherhood = survey.merge(
    participation,
    on="Client ID",
    how="left",
    validate="one_to_one"
)

In [9]:
fatherhood.head(0)

Empty DataFrame
Columns: [Client ID, Office Location, Program, Client Population, Enrollment Date, Current Client Status, Client Status Change Date, Exit Survey Completion Date, ACS-Age, ACS-Ethnicity, ACS-Race 1, ACS-Race 2, ACS-Race 3, ACS-Race 4, ACS-Race 5, ACS-Race 6, ACS-Language Primary, ACS-Assist TANF, ACS-Assist SSI, ACS-Assist SSDI, ACS-Assist SNAP, ACS-Assist WIC, ACS-Assist Unemp Ins, ACS-Assist Sect8, ACS-Assist Cash, ACS-Assist Child Sup, ACS-Living Situation, ACS-Living Area, ACS-Highest Degr, ACS-Employment Status 1, ACS-Employment Status 2, ACS-Employment Status 3, ACS-Employment Status 4, ACS-Employment Status 5, ACS-Employment Status 6, ACS-Children Biological, ACS-Children Adopted, ACS-Children Other Live, ACS-Hear About 1, ACS-Hear About 2, ACS-Hear About 3, ACS-Hear About 4, ACS-Hear About 5, ACS-Hear About 6, ACS-Hear About 7, ACS-Hear About 8, ACS-Hear About 9, ACS-Hear About 10, ENT-Child1 Argue, ENT-Hit Child1, ENT-Yell Child1, ENT-Talk Wrong Child1, ENT-Child1_12p TV, ENT-Child1_12p Walk, ENT-Child1_12p Meal, ENT-Child1_12p Park, ENT-Child1_12p Sports, ENT-Child1_12p Watched, ENT-Child1_12p Games, ENT-Child1_12p Hug, ENT-Child1_12p Encourage, ENT-Child1_12p Love, ENT-Child1_12p Choices, ENT-Child1_6_12 Toys, ENT-Child1_6_12 Meals, ENT-Child1_6_12 Hug, ENT-Child1_6_12 Watched, ENT-Child1_6_12 Read, ENT-Child1_6_12 Wait, ENT-Child1_6_12 Encouraged, ENT-Child1_6_12 Love, ENT-Child1_6_12 Talk, ENT-Child1_1_6 Toys, ENT-Child1_1_6 Meals, ENT-Child1_1_6 Hug, ENT-Child1_1_6 Watched, ENT-Child1_1_6 Rough, ENT-Child1_1_6 Read, ENT-Child1_1_6 Wait, ENT-Child1_1_6 Encouraged, ENT-Child1_1_6 Love, ENT-Child1_1_6 Talk, ENT-Child1_L1 Fed, ENT-Child1_L1 Praised, ENT-Child1_L1 Watched M, ENT-Child1_L1 Sleep, ENT-Child1_L1 Toys, ENT-Child1_L1 Talk, ENT-Child1_L1 Hug, ENT-Child1_L1 Love, ENT-Child1_L1 Sung, ENT-Child1_L1 Read, ENT-Child1_L1 Stories, ENT-Child2 Argue, ENT-Hit Child2, ENT-Yell Child2, ENT-Talk Wrong Child2, ENT-Child2_12p TV, ENT-Child2_12p Walk, ENT-Child2_12p Meal, ...]
Index: []

[0 rows x 227 columns]

In [12]:
fatherhood_clean = fatherhood.drop(
    columns=[
        "Program",
        "Client Population",
        "Client Status Change Date"
    ]
)

In [13]:
fatherhood_clean.head(0)

Empty DataFrame
Columns: [Client ID, Office Location, Enrollment Date, Current Client Status, Exit Survey Completion Date, ACS-Age, ACS-Ethnicity, ACS-Race 1, ACS-Race 2, ACS-Race 3, ACS-Race 4, ACS-Race 5, ACS-Race 6, ACS-Language Primary, ACS-Assist TANF, ACS-Assist SSI, ACS-Assist SSDI, ACS-Assist SNAP, ACS-Assist WIC, ACS-Assist Unemp Ins, ACS-Assist Sect8, ACS-Assist Cash, ACS-Assist Child Sup, ACS-Living Situation, ACS-Living Area, ACS-Highest Degr, ACS-Employment Status 1, ACS-Employment Status 2, ACS-Employment Status 3, ACS-Employment Status 4, ACS-Employment Status 5, ACS-Employment Status 6, ACS-Children Biological, ACS-Children Adopted, ACS-Children Other Live, ACS-Hear About 1, ACS-Hear About 2, ACS-Hear About 3, ACS-Hear About 4, ACS-Hear About 5, ACS-Hear About 6, ACS-Hear About 7, ACS-Hear About 8, ACS-Hear About 9, ACS-Hear About 10, ENT-Child1 Argue, ENT-Hit Child1, ENT-Yell Child1, ENT-Talk Wrong Child1, ENT-Child1_12p TV, ENT-Child1_12p Walk, ENT-Child1_12p Meal, ENT-Child1_12p Park, ENT-Child1_12p Sports, ENT-Child1_12p Watched, ENT-Child1_12p Games, ENT-Child1_12p Hug, ENT-Child1_12p Encourage, ENT-Child1_12p Love, ENT-Child1_12p Choices, ENT-Child1_6_12 Toys, ENT-Child1_6_12 Meals, ENT-Child1_6_12 Hug, ENT-Child1_6_12 Watched, ENT-Child1_6_12 Read, ENT-Child1_6_12 Wait, ENT-Child1_6_12 Encouraged, ENT-Child1_6_12 Love, ENT-Child1_6_12 Talk, ENT-Child1_1_6 Toys, ENT-Child1_1_6 Meals, ENT-Child1_1_6 Hug, ENT-Child1_1_6 Watched, ENT-Child1_1_6 Rough, ENT-Child1_1_6 Read, ENT-Child1_1_6 Wait, ENT-Child1_1_6 Encouraged, ENT-Child1_1_6 Love, ENT-Child1_1_6 Talk, ENT-Child1_L1 Fed, ENT-Child1_L1 Praised, ENT-Child1_L1 Watched M, ENT-Child1_L1 Sleep, ENT-Child1_L1 Toys, ENT-Child1_L1 Talk, ENT-Child1_L1 Hug, ENT-Child1_L1 Love, ENT-Child1_L1 Sung, ENT-Child1_L1 Read, ENT-Child1_L1 Stories, ENT-Child2 Argue, ENT-Hit Child2, ENT-Yell Child2, ENT-Talk Wrong Child2, ENT-Child2_12p TV, ENT-Child2_12p Walk, ENT-Child2_12p Meal, ENT-Child2_12p Park, ENT-Child2_12p Sports, ENT-Child2_12p Watched, ...]
Index: []

[0 rows x 224 columns]

## Replace Coded Survey Responses

In [14]:
fatherhood_clean["Current Client Status"] = fatherhood_clean["Current Client Status"].replace({
    1: "Applicant Pending Enrollment",
    4: "Duplicate Confirmed",
    5: "Completed/Graduated",
    6: "Drop Out",
    7: "Non-responsive",
    8: "Temporary Hold",
    9: "Moved out of Area",
    10: "Incarcerated",
    12: "Consent Revoked",
    17: "Deceased",
})

In [15]:
fatherhood_clean["ACS-Ethnicity"] = fatherhood_clean["ACS-Ethnicity"].replace({
    1: "Not Hispanic or Latino",
    2: "Hispanic or Latino",
})

In [17]:
fatherhood_clean["ACS-Language Primary"] = fatherhood_clean["ACS-Language Primary"].replace({
    1: "English",
    2: "Spanish",
    3: "English and Spanish equally",
    4: "Other",
})

In [18]:
fatherhood_clean["ACS-Living Situation"] = fatherhood_clean["ACS-Living Situation"].replace({
    1: "Own Home",
    2: "Rent",
    3: "Live with Parents or Relatives",
    4: "Live with Friends",
    5: "Shelter/Halfway House/Treatment Facility",
    6: "Unhoused",
    7: "Incarcerated",
    8: "Other",
})

In [19]:
fatherhood_clean["ACS-Living Area"] = fatherhood_clean["ACS-Living Area"].replace({
    1: "Large City",
    2: "Suburb of a Large City",
    3: "Small City",
    4: "Rural",
})

In [20]:
fatherhood_clean["ACS-Highest Degr"] = fatherhood_clean["ACS-Highest Degr"].replace({
    1: "None",
    2: "GED",
    3: "High School Diploma",
    4: "Vocational/Technical Cert",
    5: "Some College, no Degree",
    6: "Associate's Degree",
    7: "Bachelor's Degree",
    8: "Master's/Advanced Degree",
})

## Delete rows with confirmed duplicate status/revoked consent/pending enrollment 

(indicates no other response data)

In [22]:
counts = fatherhood_clean['Current Client Status'].value_counts()
counts

Current Client Status
Completed/Graduated             1139
Non-responsive                   252
Moved out of Area                 86
Drop Out                          49
Incarcerated                       9
Deceased                           5
Applicant Pending Enrollment       4
Consent Revoked                    2
Temporary Hold                     2
Duplicate Confirmed                1
Name: count, dtype: int64

In [29]:
exclude = ["Applicant Pending Enrollment", "Consent Revoked", "Duplicate Confirmed"]

fatherhood_clean = fatherhood_clean[fatherhood_clean["Current Client Status"].isin(exclude) == False]

In [32]:
counts2 = fatherhood_clean['Current Client Status'].value_counts()
counts2

Current Client Status
Completed/Graduated    1139
Non-responsive          252
Moved out of Area        86
Drop Out                 49
Incarcerated              9
Deceased                  5
Temporary Hold            2
nan                       1
Name: count, dtype: int64

In [33]:
fatherhood_clean.to_csv('Fatherhood Cleaned.csv', index=False)